In [1]:
import gym
import time
import random
import numpy as np
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v1")

/usr/local/lib/python3.7/dist-packages/gym/core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
/usr/local/lib/python3.7/dist-packages/gym/wrappers/step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."


In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

In [4]:
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_step_per_episode = 100

learning_rate = 0.1
discount_rate= 0.9

exploration_rate = 0.1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [6]:
reward_all_episodes = []

In [7]:
for episode in range(num_episodes):

  state = env.reset()

  done = False
  rewards_current_episode = 0

  for step in range(max_step_per_episode):

    exploration_rate_threshold = random.uniform(0,1)
    if exploration_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state,:])
    else:
      action = env.action_space.sample()

    new_state, reward, done, info = env.step(action)

    q_table[state, action] = (1-learning_rate)*q_table[state,action] + learning_rate*(reward + discount_rate*np.max(q_table[new_state, :]))

    state = new_state
    rewards_current_episode += reward

    if done == True:
      break

  exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate)*np.exp(-exploration_decay_rate*episode)

  reward_all_episodes.append(rewards_current_episode)

In [8]:
rewards_per_thosand_episodes = np.split(np.array(reward_all_episodes),num_episodes/1000)
count = 1000
print("********* Inicio ********\n")
for r in rewards_per_thosand_episodes:
  print(count, ": ",str(sum(r/1000)))
  count += 1000

print("********* Tabla ********\n")
print(q_table)

********* Inicio ********

1000 :  0.0
2000 :  0.0
3000 :  0.0
4000 :  0.0
5000 :  0.0
6000 :  0.0
7000 :  0.0
8000 :  0.0
9000 :  0.0
10000 :  0.0
********* Tabla ********

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Es momento de probar nuestros resultados:

In [10]:
for episode in range(3):
  state = env.reset()
  done = False
  print("Episode: "+str(episode+1))
  time.sleep(1)

  for step in range(max_step_per_episode):
    clear_output(wait=True)
    time.sleep(0.3)

    action = np.argmax(q_table[state,:]) # For the state we are, all posible actions
    new_state, reward, done, info = env.step(action)
    print(new_state)

    if done:
      clear_output(wait=True)
      if reward == 1:
        print("Goal reached")
        time.sleep(3)
      else:
        print("Failed, it fall into a hole")
        time.sleep(3)
      
      clear_output(wait=True)
      break

    state = new_state
  
env.close()


Failed, it fall into a hole
